### ISSUE TITLE
Expose exports.getFirstNameFromFullName() so it can be used

### ISSUE THREAD

**Issue by flesler** [davidemiceli/gender-detection#2]
It'd make sense sometimes to store the "canonical" firstName that lead to the gender returned as well, it's trivial to expose this function in case it wants to be used in conjunction

**Comment by davidemiceli** [comment]
Hi @flesler, thanks to you for the feedback!
If you want the function to get the first name exposed, I can do: It is trivial as you said...

**Comment by davidemiceli** [comment]
@flesler you can update your package with npm to 0.1.0 version to see the updates you asked for...

**Comment by flesler** [comment]
I will, thanks for adding the change and so quickly :+1:
